#*******************************************************************************
# Licensed Materials - Property of IBM
# (c) Copyright IBM Corp. 2026. All Rights Reserved.
#
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# Contract with IBM Corp.
#*******************************************************************************
---
apiVersion: deploy.ibm.com/v1
kind: DeploymentMethod
metadata:
  name: 'CICS/DB2/IMS/zOSConnect deployment method'
  version: '1.0.0'

activities:
  # Load all deployment configurations first
  - name: LOAD_CONFIG
    short_name: LOAD_CONFIG
    description: |
      Load the generic Wazi Deploy Configuration variables
      Specific for the Python implementation
    plan_tags:
      - always
    actions:
      - name: READ_CONFIGURATION
        short_name: READ_CONFIG
        steps:
          # Load global include configuration from central location
          - name: INCLUDE_GLOBAL_CONFIG
            short_name: INCLUDE_GLOBAL_CFG
            description: |
              Load global include configuration global_initialization.yml from central location
            properties:
              - key: template
                value: include_vars
              - key: var_include_vars
                value: include_global_config
          # Load application specific settings from central location
          #  these are environment specific
          - name: INCLUDE_APPLICATION_VARIABLES
            short_name: INCLUDE_APP_VARS
            description: |
              Load environment specific application overrides from central location
            properties:
              - key: template
                value: include_vars
              - key: var_include_vars
                value: include_application_vars
          # Load middleware configurations such as Db2 and CICS settings that configure the Wazi Deploy building blocks
          #  environment specific config are passed via the environment configurations
          - name: INCLUDE_MIDDLEWARE_CONFIG
            short_name: INCLUDE_MIDDLEWARE_CFG
            description: |
              Load global middleware configuration configuring the Wazi Deploy building blocks
            properties:
              - key: template
                value: include_vars
              - key: var_include_vars
                value: include_middleware_cfg
          # Load global and common variables such as types mappings or dataset configurations
          - name: INCLUDE_COMMON_CONFIG
            short_name: INCLUDE_COMMON_CFG
            description: |
              Load global configuration for Wazi Deploy Core building blocks such as type mappings and dataset configurations
            properties:
              - key: template
                value: include_vars
              - key: var_include_vars
                value: include_common_cfg

  - name: PACKAGE
    short_name: PACKAGE
    description: |
      This activity expands the package into the working directory
    actions:
      - name: EXPAND_PACKAGE
        short_name: EXPAND_PACKAGE
        steps:
          - name: PACKAGE
    plan_tags:
      - always

  - name: CICS_REGION
    short_name: CICS_REGION
    description: |
      This activity applies CICS Resource Builder configurations to the target CICS region
    is_artifact: True
    types:
      - name: "CSD"
    actions:
      - name: CSD
        states:
          - UNDEFINED
        steps:
         - name: UPDATE
           is_artifact: true
           properties:
             - key: template
               value: job_submit
             - key: var_job_submit
               value: csd_update_template

  # activity to process DBRMs always first
  #  * A tag is used to be able to run these actions only and skip others 
  #    in it's own run
  #  * member_copy is configured to move the DBRM into a temp library first
  - name: DBRMS
    description: |
      This activity is dedicated to DBRM bind modules and will process DBRM members of the package first using dedicated PDS libraries 
    short_name: DBRMS
    actions:
      # Manage deletions of DBRMS
      - name: DELETE
        short_name: DELETE
        description: |
          This action is applicable when the artifacts are deleted
        states:
          - DELETED
        steps:
          - name: MEMBER_ARCHIVE
            short_name: MEMBER_ARCHIVE
            description: |
              This step backs up already installed artifacts into the backup PDS
          - name: MEMBER_DELETE
            short_name: MEMBER_DELETE
            description: |
              This step deletes the artifacts
      # Manage Updates
      - name: UPDATE
        short_name: UPDATE
        description: |
          This action is applicable when we add new or changed artifacts.
        steps:
          - name: MEMBER_COPY
            short_name: MEMBER_COPY
            description: |
              This step copies DBRMs into temporary PDS library. See 'type_dbrm_temp'
            properties:
              - key: var_type
                value: type_dbrm_temp
          - name: BIND_PACKAGE
            short_name: BIND_PACKAGE
            description: |
              This step performs the DB2 Bind package operations for all DBRM members of the package
            properties:
              - key: template
                value: db2_bind_package
              - key: var_type
                value: type_dbrm_temp
              - key: var_template_name
                value: db2_bind_package_template
          - name: BIND_PLAN
            short_name: BIND_PLAN
            description: |
              This step performs the DB2 Bind plan operations for all DBRM members of the package
            properties:
              - key: template
                value: db2_bind_plan
              - key: var_type
                value: type_dbrm_temp
              - key: var_template_name
                value: db2_bind_plan_template
            plan_tags:
            - never
    types:
      - name: "DBRM"
    is_artifact: True
    plan_tags:
      - db2

  # General deployment routines including taking backups
  - name: DEPLOY_MODULES
    short_name: DEPLOY_MODULES
    description: |
      This activity is deploys artifacts into the target PDS libraries
    actions:
      - name: DELETE
        short_name: DELETE
        description: |
          This action is applicable when the artifacts are deleted
        states:
          - DELETED
        steps:
          - name: MEMBER_ARCHIVE
            short_name: MEMBER_ARCHIVE
            description: |
              This step backs up already installed artifacts into the backup PDS
          - name: MEMBER_DELETE
            short_name: MEMBER_DELETE
            description: |
              This step deletes the artifacts
      - name: UPDATE
        short_name: UPDATE
        description: |
          This action is applicable when we add new or changed artifacts.
        steps:
          - name: MEMBER_ARCHIVE
            short_name: MEMBER_ARCHIVE
            description: |
              This step backs up already installed artifacts into the backup PDS
          - name: MEMBER_COPY
            short_name: MEMBER_COPY
            description: |
              This step do the copy of artifacts into PDSs
    types:
      - name: "LOAD"
      - name: "DBRM"
      - name: "CICSLOAD"
      - name: "MAPLOAD"
      - name: "JCL"
      - name: "PSBLOAD"
      - name: "DBDLOAD"
      - name: "IMSLOAD"
    is_artifact: True
    plan_tags:
      - deploy

  # ROLLBACK activities
  - name: ROLLBACK_MODULES
    short_name: ROLLBACK_MODULES
    description: |
      This action is applicable when when restoring files from the backup 
      datasets. It is only executed when plan_tags 'restore' is provided.   
    actions:
      - name: RESTORE
        description: |
          Retrieve members from backup dataset
        steps:
          - name: MEMBER_RESTORE
            short_name: MEMBER_RESTORE
            description: |
              This step restores the backup from the backup PDS
      # Invoke Bind operations
      - name: BIND
        types:
         - name: "DBRM"
        description: |
          This action runs Db2 Bind package and plan for restored DBRM members
        steps:
          - name: BIND_PACKAGE
            short_name: BIND_PACKAGE
            description: |
              This step performs the DB2 Bind package operations for restored DBRM members
            properties:
              - key: template
                value: db2_bind_package
              - key: var_template_name
                value: db2_bind_package_template
          - name: BIND_PLAN
            short_name: BIND_PLAN
            description: |
              This step performs the DB2 Bind plan operations for restored DBRM members
            properties:
              - key: template
                value: db2_bind_plan
    types:
      - name: "LOAD"
      - name: "DBRM"
      - name: "CICSLOAD"
      - name: "MAPLOAD"
      - name: "JCL"
    is_artifact: True
    plan_tags:
      - restore
      - never

  # JCL Verification operation
  - name: VERIFICATION
    short_name: VERIFICATION
    description: |
      This action block verifies that the deployed JCLs are correct.
      It uses the JCL Expert to scan and validate them. This showcases 
      how the conditional deployment 'loop' keyword can be used. (Optional).
    types:
      - name: "JCL"
    actions:
      - name: JCLEXPERT
        short_name: JCLEXPERT
        description: |
          Invoke JCL expert interface for each deployed JCL member
        steps:
          - name: SCAN_JCL
            short_name: SCAN_JCL
            description: | 
              This step loops over all JCL members and performs an JCL Expert scan
            is_artifact: True
            types:
              - name: "JCL"
            loop:
              loop_query: current_plan_step.artifacts
              loop_var: jcl_member
            when:
              - wd_query[[ length ( current_plan_step.artifacts) ]] != 0
            properties:
              - key: template
                value: job_submit
              - key: var_job_submit
                value: jcl_expert_verification
    when:
      - environment.run_jcl_expert

  # CICS online activation
  - name: CICS_ACTIVATION
    short_name: CICS_ACTIVATION
    description: |
      This activity is dedicated for deployed or restored CICS artifacts.
    plan_tags:
      - restore
    types:
      - name: "CICSLOAD"
      - name: "MAPLOAD"
    actions:
      - name: UPDATE
        short_name: UPDATE
        description: |
          Update CICS runtime
        states:
          - UNDEFINED
        steps:
          - name: PROG_UPDATE
            short_name: PROG_UPDATE
            description: |
              Refreshes CICS programs and maps via the CMCI interface
            properties:
              - key: "template"
                value: "cics_cmci_prog_update"
    is_artifact: True

  - name: IMS_ACB_MANAGEMENT
    description: |
        This activity is dedicated to the deployment of IMS with Management ACBs
    actions:
          - name: IMS_ACBGEN
            description: |
              This action is applicable when we add or modify artifacts.
            steps:
            - name: ACBGEN
              description: |
                This step build the ACBs
              properties:
              - key: "template"
                value: "ims_acb_gen"
              retry:
                max_attempt: 2
                interval: 1
    types:
        - name: 'PSBLOAD'
        - name: 'DBDLOAD'
    is_artifact: True
    tags:
      - ims_acb_management
      - ims
      

  - name: IMS_OLCUTL_MANAGEMENT
    description: |
      This activity is dedicated to the deployment of IMS artifacts to the active lib
    actions:
        - name: IMS_OLCUTL
          description: |
            This action is applicable when we add or modify artifacts.
          steps:
          - name: IMS_OLCUTL
            description: |
              This step builds the execute the OLCUTL procedure
            properties:
            - key: "template"
              value: "ims_olcutl"
            - key: "var_ims_olcutl"
              value: "ims_olcutl_cat"
            when:
              - wd_query[[ length ( current_plan_step.artifacts) ]] != 0
    types:
      - name: 'PSBLOAD'
      - name: 'DBDLOAD'
      - name: 'IMSLOAD'
    is_artifact: True
    tags:
    - ims_oclutl_management
    - ims
    - never

  - name: IMS_CATALOG_MANAGEMENT
    description: |
      This activity is dedicated to the deployment of IMS with Catalog Management ACBs
    actions:
          - name: IMS_CATALOG
            description: |
              This action is applicable when we add or modify artifacts.
            steps:
            - name: IMS_CATALOG
              description: |
                This step activates all new IMS artifacts
              properties:
              - key: "template"
                value: "ims_catalog_populate"
              when:
                - wd_query[[ length ( current_plan_step.artifacts) ]] != 0
    types:
        - name: 'PSBLOAD'
        - name: 'DBDLOAD'
    is_artifact: True
    tags:
      - ims_catalog_management
      - ims

  - name: IMS_JCL_POPULATE_MANAGEMENT
    description: |
      This activity is dedicated to the deployment of IMS with Management ACBs
    actions:
        - name: CAT_POPULATE
          description: |
            This action is applicable when we add or modify artifacts.
          steps:
          - name: CAT_POPULATE
            description: |
              This step build the ACBs and populate catalogue
            properties:
              - key: template
                value: job_submit
              - key: var_job_submit
                value: jcl_ims_catpop
            retry:
              max_attempt: 2
              interval: 1
            when:
              - wd_query[[ length ( current_plan_step.artifacts) ]] != 0
    types:
      - name: 'PSBLOAD'
      - name: 'DBDLOAD'
    is_artifact: True
    tags:
    - ims_jcl_catpop_management
    - ims
    - never

  - name: IMS_MACLIB_MANAGEMENT
    description: |
      This activity is dedicated to the update of MacLib
    actions:
        - name: IMS_MACLIB
          description: |
            This action is applicable when we add or modify artifacts.
          steps:
          - name: IMS_MACLIB
            description: |
              This step activates all new IMS artifacts
            properties:
              - key: template
                value: job_submit
              - key: var_job_submit
                value: jcl_ims_maclib
            when:
              - wd_query[[ length ( current_plan_step.artifacts) ]] != 0
    types:
      - name: 'PSBLOAD'
      - name: 'DBDLOAD'
    is_artifact: True
    tags:
    - ims_maclib_management
    - ims

  - name: IMS_SPOC_MANAGEMENT
    description: |
      This activity is dedicated to the update of MacLib
    actions:
        - name: IMS_SPOC
          description: |
            This action is applicable when we add or modify artifacts.
          steps:
          - name: IMS_SPOC
            description: |
              This step activates all new IMS artifacts
            properties:
              - key: template
                value: job_submit
              - key: var_job_submit
                value: jcl_ims_spoc
            when:
              - wd_query[[ length ( current_plan_step.artifacts) ]] != 0
    types:
      - name: 'PSBLOAD'
      - name: 'DBDLOAD'
      - name: 'IMSLOAD'
    is_artifact: True
    tags:
    - ims_spoc_management
    - ims

  - name: 'Deploy IMS JAR'
    description: 'Copy the IMS Java JMP JAR to the USS classpath directory'
    actions:
        - name: 'Copy to USS'
          steps:
          - name: USS_COPY
    is_artifact: True
    types:
       - name: 'jar'
    tags:
    - deploy_jar
    - deploy

  - name: 'Deploy WAR files'
    description: 'Copy the z/OS Connect WAR files into the destination folder'
    actions:
        - name: 'Copy to USS'
          steps:
          - name: USS_ARCHIVE
          - name: USS_COPY
          - name: USS_RESTORE
            plan_tags:
            - restore
            - never
    types:
       - name: 'war'
    is_artifact: True
    tags:
    - zosconnect_copy
    - deploy

  - name: 'Deploy Config Files'
    description: 'Process and deploy z/OS Connect configuration files with variable substitution'
    actions:
        - name: 'Process z/OS Connect config files'
          steps:
          - name: ZOS_CONNECT_CONFIG
            properties:
            - key: "template"
              value: "template"
            - key: "var_template_name"
              value: "template_name_zosconnect_config"
            - key: "path_filter"
              value: '^(?!.*-frontend).*\.war$'
            loop:
               loop_query: "wd_query[[ current_plan_step.artifacts[].name ]]"
               loop_var: "api_name"
            when:
              - wd_query[[ length ( current_plan_step.artifacts) ]] != 0
    types:
       - name: 'war'
    is_artifact: True
    tags:
    - zosconnect_config
    - deploy

  - name: 'Refresh z/OS Connect'
    description: 'Refresh z/OS Connect config and application'
    actions:
        - name: REFRESH_ZOS_CONNECT
          steps:
          - name: 'Refresh z/OS Config'
            properties:
            - key: 'template'
              value: 'system_command'
            - key: 'var_system_command'
              value: 'system_command_refresh_config'
            - key: "path_filter"
              value: '^(?!.*-frontend).*\.war$'
            when:
              - wd_query[[ length ( current_plan_step.artifacts) ]] != 0
          - name: 'Refresh z/OS Application'
            properties:
            - key: 'template'
              value: 'system_command'
            - key: "path_filter"
              value: '^(?!.*-frontend).*\.war$'
            - key: 'var_system_command'
              value: 'system_command_refresh_apps'
            when:
              - wd_query[[ length ( current_plan_step.artifacts) ]] != 0
    types:
       - name: 'war'
    is_artifact: True
    tags:
    - zosconnect_refresh
    - deploy
    
  - name: 'Refresh Fronted'
    description: 'Refresh Fronted application'
    actions:
        - name: REFRESH_FRONTED
          steps:
          - name: 'Refresh Fronted'
            properties:
            - key: 'template'
              value: 'system_command'
            - key: "path_filter"
              value: '.*-frontend.*\.war$'
            - key: 'var_system_command'
              value: 'system_command_refresh_fronted'
            when:
              - wd_query[[ length ( current_plan_step.artifacts) ]] != 0
    types:
       - name: 'war'
    is_artifact: True
    tags:
    - fronted_refresh
    - deploy

# Made with Bob
