#*******************************************************************************
# Licensed Materials - Property of IBM
# (c) Copyright IBM Corp. 2026. All Rights Reserved.
#
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# Contract with IBM Corp.
#*******************************************************************************

# Notes:
# 
# Upload strategy:
#  Default: Upload files is via ZOAU python APIs by. native_copy only on selected operations where datasets
#  without any shared allocations can be guaranteed (probably JCL).
#
# Concurrent access check:
#  Default: Check for concurrent allocations on target datasets (not applicable when using native_copy). Deployment fails on concurrent access.
#  Exceptions: Deploying into Online regions where concurrent allocations are expected
# 

bankz_pds_load_spec:
  type: LIBRARY
  space_primary: 100CYL
  space_secondary: 20CYL
  record_format: U
  record_length: 0
  block_size: 32760

types:
  - pattern: .*\.LOAD$ 
    pds: 
      name: "{{ hlq }}.LOAD"
      backup: "{{ hlq }}.BACK.LOAD"
      spec: "{{ bankz_pds_load_spec }}"
    is_load: true
    force_lock: true
    force: true
    use_native_copy: true
  - pattern: .*\.CICSLOAD$
    pds: 
      name: "{{ hlq }}.LOADLIB"
      backup: "{{ hlq }}.BACK.LOADLIB"
      spec: "{{ bankz_pds_load_spec }}"
    is_load: true
    force_lock: true
    force: true
    use_native_copy: true
    cics_systems:
      - "{{ cics_sys_def }}"
  - pattern: .*\.MAPLOAD$
    pds: 
      name: "{{ hlq }}.LOADLIB"
      backup: "{{ hlq }}.BACK.LOADLIB"
      spec: "{{ bankz_pds_load_spec }}"
    is_load: true
    force_lock: true
    use_native_copy: true
    cics_systems:
      - "{{ cics_sys_def }}"
  - pattern: .*.DBRM$
    pds: 
      name: "{{ hlq }}.DBRM"
      backup: "{{ hlq }}.BACK.DBRM"
      spec: "{{ common_pds_binary_spec }}"
    is_binary: true
    force_lock: false
    use_native_copy: true
    db2_systems:
      - "{{ db2_sys_def }}"
  - pattern: .*.JCL$
    pds: 
      name: "{{ hlq }}.JCL"
      backup: "{{ hlq }}.BACK.JCL"
      spec: "{{ common_pds_txt_spec }}"
    force_lock: false
    use_native_copy: true
    text_subs: "{{ app_jcl_text_subs_patterns if app_jcl_text_subs_patterns is defined else [] }}"
  - pattern: .*.BIN$
    uss:
     directory: "{{ uss_root }}/bin/"
     directory_backup: "{{ uss_root }}/bin/back/"
     dest_mode: 0777
     artifact_mode: 0755
    is_binary: true
    use_native_copy: true
  - pattern: "SH"
    uss: 
     directory: "{{ uss_root }}/sh/"
     directory_backup: "{{ uss_root }}/sh/back/"
     dest_mode: 0777
     artifact_mode: 0755
  - pattern: .*-frontend.*\.WAR$
    uss:
       dest: '{{frontend_root}}/servers/{{frontend_server_name}}/apps'
       backup_dest: '{{frontend_root}}/backup/apps'
       mode: 0755
    mode: 0777
    is_binary: true
  - pattern: ^(?!.*-frontend).*\.WAR$
    uss:
       dest: '{{zos_connect_root}}/apps'
       backup_dest: '{{zos_connect_root}}/backup/apps'
       mode: 0755
    mode: 0777
    is_binary: true
  - pattern: .*\.IMSLOAD$
    pds:
      name: "{{ ims_hlq }}.{{ ims_datastore }}.PGMLIB"
      backup: "{{ hlq }}.BACK.PGMLIB"
      spec: "{{ bankz_pds_load_spec }}"
    is_load: true
    aliases: true
    force_lock: true
    use_native_copy: true
  - pattern: .*\.PSBLOAD$
    pds:
      name: "{{ ims_hlq }}.{{ ims_datastore }}.PSBLIB"
      backup: "{{ hlq }}.BACK.PSBLIB"
      spec: "{{ bankz_pds_load_spec }}"
    is_load: true
    is_ims_psb: true
    force_lock: true
    use_native_copy: true
  - pattern: .*\.DBDLOAD$
    pds:
      name: "{{ ims_hlq }}.{{ ims_datastore }}.DBDLIB"
      backup: "{{ hlq }}.BACK.DBDLIB"
      spec: "{{ bankz_pds_load_spec }}"
    force_lock: true
    is_load: true
    is_ims_dbd: true
    use_native_copy: true
  - pattern: .*\.JAR$
    uss:
      dest: "{{ sandbox_path }}/jars"
      backup_dest: "{{ sandbox_path }}/jars/back"
      mode: 0755
    mode: 0777
    is_binary: true
type_dbrm_temp:
  - type: "DBRM"
    pattern: .*.DBRM$
    pds: 
      name: "{{ hlq }}.TMP.DBRM"
      backup: "{{ hlq }}.BACK.TMP.DBRM"
      spec: "{{ common_pds_binary_spec }}"
    is_binary: true
    force_lock: false
    use_native_copy: true
    db2_systems:
      - "{{ db2_sys_def }}"